# -*- coding: utf-8 -*-
"""IPL Win Probability Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zbqd2bmi_Dzg_3V_PiKMO1jyWvqPXInQ
"""

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

match = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/IISc - Cricket Predictor/matches.csv')

delivery = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/IISc - Cricket Predictor/deliveries.csv')

match.head()

match.shape

delivery.head()

total_score_df0 = delivery.groupby(['match_id','inning']).sum()['total_runs'].reset_index()

total_score_df0

total_score_df = total_score_df0[total_score_df0['inning'] == 1]

match_df = match.merge(total_score_df[['match_id','total_runs']],left_on='id',right_on ='match_id')

match_df

match_df['team1'].unique()

teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals'
]

match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

match_df.shape

match_df = match_df[match_df['dl_applied'] == 0]

match_df = match_df[['match_id','city','winner','total_runs']]

delivery_df = match_df.merge(delivery,on='match_id')

delivery_df = delivery_df[delivery_df['inning'] == 2]

delivery_df

delivery_df['total_runs_y'] = pd.to_numeric(delivery_df['total_runs_y'])

delivery_df['current_score'] = delivery_df.groupby('match_id')['total_runs_y'].cumsum()

delivery_df

delivery_df['runs_left'] = delivery_df['total_runs_x'] - delivery_df['current_score']

delivery_df

delivery_df['balls_left'] = 126 - (delivery_df['over']*6 + delivery_df['ball'])

delivery_df

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].fillna("0")

delivery_df

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x:x if x == "0" else "1")

delivery_df

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].astype('int')

wickets = delivery_df.groupby('match_id')['player_dismissed'].cumsum().astype(int).values

delivery_df['wickets'] = 10 - wickets

delivery_df

def result(row):
    return 1 if row['batting_team'] == row['winner'] else 0

delivery_df['result'] = delivery_df.apply(result,axis=1)

delivery_df

dataset = delivery_df[['batting_team','bowling_team','city','runs_left','balls_left','wickets','total_runs_x','result']]

dataset

X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

X

X.shape

y

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

X_train

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer([('trf',OneHotEncoder(sparse=False,drop=None),['batting_team','bowling_team','city'])],remainder='passthrough')

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

pipe = Pipeline(steps=[('step1',trf),('step2',LogisticRegression(solver='liblinear'))])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

teams

delivery_df['city'].unique()

import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

